### ISSUE TITLE
rails has been updated since lab was written - 2 tweaks needed to pass

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/rails-blog-scaffold#10]
after running the 'single command' that is supposed to get all the tests passing, you have to make the following changes:
1. class Post in models must be changed to inherit from ActiveRecord::Base, not Application Record 
`class Post < ActiveRecord::Base
end`

2. form.html.erb first line must be changed to read: 
`<%= form_for(@post) do |form|%>`

got this info from Austin at AAQ.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
