### ISSUE TITLE
Took Longer Than 5 Minutes

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/rails-blog-scaffold#11]
Hey there, 

I would not have figured out this lab without the solution, because there is no discussion of the `_form.html.erb` file. I have no idea what it's supposed to look like, so there's no reason to think I would be able to solve errors caused by it. Either teach it, or include directions regarding that file in the ReadMe instructions.

Best,
A

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
