### ISSUE TITLE
Rails generator is slightly off

### ISSUE THREAD

**Issue by daschne8** [learn-co-curriculum/rails-blog-scaffold#12]
I assumed they just wanted us to run the command `rails g scaffold  Post title:string description:text --no-test-framework` to pass the lab but,  my model post.rb file is generated inheriting from ApplicationRecord instead of ActiveRecord::Base and the  views _form.html.erb file is slightly different as well. From looking around it looks like these changes were implemented in rails 5 and the lab tests might be for rails 4.x

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
