### ISSUE TITLE
The lab still need to be updated

### ISSUE THREAD

**Issue by PrincessLaurora** [learn-co-curriculum/rails-blog-scaffold#13]
After I run the command  _rails g scaffold Post title:string description:text --no-test-framework_ I've got 12 errors which I can't figure out how to correct.
I have run bundle update (in case it was a gem issue)and the errors where even more (17).
I am experiencing so many issues with this Rails unit, it needs a good update.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
