### ISSUE TITLE
Rails Blog Scaffold

### ISSUE THREAD

**Issue by Poliarddjimmy** [learn-co-curriculum/rails-blog-scaffold#14]
Nothing Happen when i pass the command rails generate scaffold Apartment address:string price:float description:text image_url:string --no-test-framework on my terminal

**Comment by lizbur10** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via a quick edit, or bugs with the Learn platform (such as lights not turning green or IDE issues).

This issue would be perfect for the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
