### ISSUE TITLE
Lab Tests Do not pass with one line run as stated in the lesson

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/rails-blog-scaffold#15]
So I ran the `rails g scaffold Post title description:text --no-test-framework` command which was supposed to make the lab tests all pass.  (Oh and I also ran `rake db:migrate` after that) 

Upon running `learn`, I had multiple test failures. 

My guess is that some of the changes in the new Rails version I'm using (5.2.2) caused this to no longer pass with such ease.  🤷‍♂️

Almost all the errors were complaining about `uninitialized constant ApplicationRecord` (see below)
```rspec
PostsController
  GET index
    assigns all posts as @posts (FAILED - 1)
  GET show
    assigns the requested post as @post (FAILED - 2)
  GET new
    assigns a new post as @post (FAILED - 3)
  GET edit
    assigns the requested post as @post (FAILED - 4)
  POST create
    with valid params
      creates a new Post (FAILED - 5)
      assigns a newly created post as @post (FAILED - 6)
      redirects to the created post (FAILED - 7)
  PUT update
    with valid params
      updates the requested post (FAILED - 8)
      assigns the requested post as @post (FAILED - 9)
      redirects to the post (FAILED - 10)
  DELETE destroy
    destroys the requested post (FAILED - 11)
    redirects to the posts list (FAILED - 12)

Posts
  GET /posts
    works! (now write some real specs) (FAILED - 13)

PostsController
  routing
    routes to #index
    routes to #new
    routes to #show
    routes to #edit
    routes to #create
    routes to #update
    routes to #destroy

posts/edit
  renders the edit post form (FAILED - 14)

posts/index
  renders a list of posts (FAILED - 15)

posts/new
  renders new post form (FAILED - 16)

posts/show
  renders attributes in <p> (FAILED - 17)

Failures:

  1) PostsController GET index assigns all posts as @posts
     Failure/Error: class Post < ApplicationRecord
     
     NameError:
       uninitialized constant ApplicationRecord
```

To fix this error I had to update the Post model to inherit from `ActiveRecord::Base` instead of `ApplicationRecord` (It looks like the scaffold generator defaulted the Post model to inherit from ApplicationRecord)

Doing this fixed most of the test errors except to two (which were complaining of the same issue:

```rspec
PostsController
  GET index
    assigns all posts as @posts
  GET show
    assigns the requested post as @post
  GET new
    assigns a new post as @post
  GET edit
    assigns the requested post as @post
  POST create
    with valid params
      creates a new Post
      assigns a newly created post as @post
      redirects to the created post
  PUT update
    with valid params
      updates the requested post
      assigns the requested post as @post
      redirects to the post
  DELETE destroy
    destroys the requested post
    redirects to the posts list

Posts
  GET /posts
    works! (now write some real specs)

PostsController
  routing
    routes to #index
    routes to #new
    routes to #show
    routes to #edit
    routes to #create
    routes to #update
    routes to #destroy

posts/edit
  renders the edit post form (FAILED - 1)

posts/index
  renders a list of posts

posts/new
  renders new post form (FAILED - 2)

posts/show
  renders attributes in <p>

Failures:

  1) posts/edit renders the edit post form
     Failure/Error: assert_select "input#post_title[name=?]", "post[title]"
     
     Minitest::Assertion:
       Expected at least 1 element matching "input#post_title[name="post[title]"]", found 0..
       Expected 0 to be >= 1.
```
The issue was with the form partial file being rendered on the `new` and `edit` pages (`app/views/posts/_form.html.erb`)

Here is what the scaffold generator made: 
```erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
```

To fix it, the `form_with` had to be replaced with a `form_for`: 
```erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :description %>
    <%= f.text_area :description %><br>
    <%= f.submit %>
    
<% end %>
```
(note I also took out the `<div>`'s around the title and description form fields just because I wanted to)

I could totally be wrong here and maybe I didn't do the lab right, but if I did run the 1 command the lab wanted me to, then these errors will most likely cause a lot of students headaches trying to figure out what they messed up when in fact they didn't mess anything up. :( :/ 

Here is a [link to my forked Repo (so you can inspect my Gemfile, etc) ](https://github.com/jrodden1/rails-resource-and-scaffold-generator-online-web-ft-061019)

Hope this helps!

**Comment by Sdcrouse** [comment]
Just to offer another solution for the ApplicationRecord problem, I made a `/models/application_record.rb` file. Then, I added this code (which I've seen in other lessons):
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
```
It's not as simple as just having the Post class inherit from `ActiveRecord::Base`, but I think it's more conventional.

Hope that helps!

**Comment by Sdcrouse** [comment]
And just for fun, I made the pages look a little nicer by adding `margin-left: 20px;` to the `/assets/stylesheets/application.css.scss` file:

```
body {
  margin-left: 20px;
  padding-top: 70px;
  padding-bottom: 30px;
}
```
Because why not? 😁

**Comment by SenseiCain** [comment]
I had this same set of issue. For the errors on post/new, and post/edit, I believe whats going on is that when you're calling the scaffold method it is using the form_with builder which is setting the id's of the inputs in a manner that is not lining up with what the Capybara tests expect.

Seems like this would work! Although, tbh I erased those tests as I knew the functionality was there. The pre-written tests were simply not lining up.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
