### ISSUE TITLE
Interesting Problem

### ISSUE THREAD

**Issue by AdamWeissman** [learn-co-curriculum/rails-blog-scaffold#22]
What everyone says below is true.  However, I deleted my repo and reforked the lab, hoping to just try again (I had made a mess of the code base).  Anyways, what I discovered was: all the tests pass perfectly when running it locally, so, I'm assuming/suspecting that there's some sort of cross referencing happening with the flatiron repo that's causing an issue.  I don't know how it all works, but the reason I think that may be the case is because it couldn't tell that I had reforked the lab.  It was telling me to "refork the lab".

**Comment by lizbur10** [comment]
Hey @AdamWeissman! 

Hmm, interesting. I was not able to recreate this issue but we've done some updating to the gems on this lab so hopefully that will fix this problem as well. I'm going to go ahead and close this issue 💙
