### ISSUE TITLE
Gemfile - gem 'sqlite3' ~> '1.3.6' issue

### ISSUE THREAD

**Issue by doosemavis** [learn-co-curriculum/rails-blog-scaffold#28]
Hi there, 

I wasn't able to get the rspec errors to display correctly until I deleted both the `thin` gem and the `~> 1.3.6` portion of the `sqlite3` gem and then run `bundle install` again.  (Also deleting `Gemfile.lock` so I could run `bundle install` again.)

Hope this can be helpful! 

Thanks again,
MD

**Comment by lizbur10** [comment]
Hey @doosemavis ! I was not able to recreate this issue but we've done some updating to the gems on this lab so hopefully that will fix this problem as well. I'm going to go ahead and close this issue 💙
