### ISSUE TITLE
Mimemagic not up to date

### ISSUE THREAD

**Issue by Christerlesn** [learn-co-curriculum/rails-blog-scaffold#29]
The mimemagic is not up to date, causing issues with the lab. It doesn't even install bundle. What I did to resolve it for myself was type `bundle update mimemagic` but I'm pretty sure I just got lucky.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe the issue to have been resolved.

Thanks for contributing to the Flatiron School curriculum. 💙
