### ISSUE TITLE
The following code needs to be substituted. Students are having issues

### ISSUE THREAD

**Issue by jasonronalddavis** [learn-co-curriculum/rails-blog-scaffold#30]
gem 'rails', '~>5.0', '>=5.0.7'

gem 'sass-rails', '~>5.0', '>=5.0.7'

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe the issue to have been resolved.

Thanks for contributing to the Flatiron School curriculum. 💙
