### ISSUE TITLE
level of difficulty

### ISSUE THREAD

**Issue by lgants** [learn-co-curriculum/rails-blog-scaffold#5]
This lab definitely took me, and many of my classmates, waaaay more than the five minutes the description says this lab should take.  Also, I still don't understand it :(

**Comment by curiositypaths** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via a quick edit, or bugs with the Learn platform (such as lights not turning green or IDE issues).

This issue would be perfect for the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
