### ISSUE TITLE
`sprockets_better_errors` causing 'undefined method lookup_asset_for_path'

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/rails-blog-scaffold#7]
[This](https://github.com/learn-co-curriculum/rails-blog-scaffold/pull/4) is still an issue and should be merged.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
