### ISSUE TITLE
Gem and config problems with this lab.

### ISSUE THREAD

**Issue by SilverBright** [learn-co-curriculum/rails-blog-scaffold#8]
I was not able to start the lab due the following problems:

- JSON gem installation error (solved just by running 'bundle update'):
"An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3' --source 'https://rubygems.org/'` succeeds before bundling."

- Factory_girl deprecation warning (solved by renaming gem in gemfile to 'factory_bot', deleting gemfile.lock, and running bundle install)
"DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions."

- configuration deprecation warning (unsolved)
"DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly."

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @SilverBright .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
