### ISSUE TITLE
Code created by rails g scaffold command not passing tests

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/rails-blog-scaffold#9]
The following changes are necessary:

In /models/post.rb, change `class Post < ApplicationRecord` to `class Post < ActiveRecord::Base`

In /views/posts/_form.html.erb, change first line to `<%= form_for post do |form| %>`

**Comment by mackenzie-km** [comment]
I had the same problem as above

Only difference is that I changed the spec to match what my form was generating. The form.html.erb hack mentioned above probably would have worked!!
